### ISSUE TITLE
CUDA out of memory upon the start of validation

### ISSUE THREAD

**Issue by ArlenCHEN** [lhoyer/HRDA#27]
Anyone has the issue of CUDA OOM when the validation starts?

```2022-11-02 14:45:20,867 - mmseg - INFO - Iter [21450/40000]	lr: 2.783e-05, eta: 1 day, 15:14:15, time: 3.936, data_time: 0.018, memory: 12106, decode.loss_seg: 0.1926, decode.acc_seg: 88.7879, decode.hr.loss_seg: 0.0364, decode.hr.acc_seg: 85.3878, src.loss_imnet_feat_dist: nan, mix.decode.loss_seg: 0.2204, mix.decode.acc_seg: 88.0694, mix.decode.hr.loss_seg: 0.0391, mix.decode.hr.acc_seg: 87.4442
[                                                  ] 0/500, elapsed: 0s, ETA:Traceback (most recent call last):
  File "run_experiments.py", line 116, in <module>
    train.main([config_files[i]])
  File "/home/ubuntu/Zheng/Softwares/HRDA/tools/train.py", line 168, in main
    train_segmentor(
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/apis/train.py", line 131, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 131, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 66, in train
    self.call_hook('after_train_iter')
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 172, in after_train_iter
    self._do_evaluate(runner)
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/core/evaluation/eval_hooks.py", line 36, in _do_evaluate
    results = single_gpu_test(
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/apis/test.py", line 67, in single_gpu_test
    result = model(return_loss=False, **data)
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/models/segmentors/base.py", line 112, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/models/segmentors/base.py", line 94, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/models/uda/uda_decorator.py", line 95, in simple_test
    return self.get_model().simple_test(img, img_meta, rescale)
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/models/segmentors/encoder_decoder.py", line 385, in simple_test
    seg_logit = self.inference(img, img_meta, rescale)
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/models/segmentors/encoder_decoder.py", line 362, in inference
    seg_logit = self.slide_inference(img, img_meta, rescale)
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/models/segmentors/encoder_decoder.py", line 280, in slide_inference
    crop_seg_logits = self.encode_decode(crop_imgs, img_meta)
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/models/segmentors/hrda_encoder_decoder.py", line 190, in encode_decode
    out = self._decode_head_forward_test(mres_feats, img_metas)
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/models/segmentors/encoder_decoder.py", line 173, in _decode_head_forward_test
    seg_logits = self.decode_head.forward_test(x, img_metas, self.test_cfg)
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/models/decode_heads/hrda_head.py", line 361, in forward_test
    test_results = self.forward(inputs)
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/models/decode_heads/hrda_head.py", line 277, in forward
    hr_seg = self.decode_hr(hr_inp, batch_size)
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/models/decode_heads/hrda_head.py", line 150, in decode_hr
    crop_seg_logits = self.head(features)
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/models/decode_heads/daformer_head.py", line 227, in forward
    x = self.fuse_layer(x)
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/models/decode_heads/daformer_head.py", line 76, in forward
    aspp_outs.extend(self.aspp_modules(x))
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Zheng/Softwares/HRDA/mmseg/models/decode_heads/aspp_head.py", line 49, in forward
    aspp_outs.append(aspp_module(x))
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/mmcv/cnn/bricks/depthwise_separable_conv_module.py", line 93, in forward
    x = self.depthwise_conv(x)
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 200, in forward
    x = self.norm(x)
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 131, in forward
    return F.batch_norm(
  File "/home/ubuntu/.conda/envs/new_da/lib/python3.8/site-packages/torch/nn/functional.py", line 2056, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 1.69 GiB (GPU 0; 14.56 GiB total capacity; 7.89 GiB already allocated; 1.01 GiB free; 12.49 GiB reserved in total by PyTorch)```

**Comment by HKQX** [comment]
I also encountered this problem in DAFomer. During the evaluation, the increase of memory caused the network to crash. I hope it can be solved

**Comment by fangzhou2000** [comment]
I have also encountered this problem. Can anyone solve it?

**Comment by lhoyer** [comment]
I haven't observed this behavior so far. Therefore, I cannot really debug it. To reduce the GPU memory during validation, you could try to disable `batched_slide`

``` python
model = dict(
    ...
    test_cfg=dict(
        ...
        batched_slide=False,
        ...
))
```

in https://github.com/lhoyer/HRDA/blob/b980dece834de0b4bad2b94fc7218ae539cdaf1e/configs/hrda/gtaHR2csHR_hrda.py#L48
